### ISSUE TITLE
Add support to path in array format

### ISSUE THREAD

**Issue by danigb** [skratchdot/object-path-get#1]
Hi, 

first of all, thanks for this tiny library. It's exactly what I'm looking for... Except for one thing: I have already the path as an array, so I have to convert it to string separated by dots, to be splited again inside your function.

So I propose (and If you agree, I can make the PR) to change the function so it accepts an array as a path (not only an string). For example: `getPath(obj, ['a', 'b'], 'default')`

I think this change makes the function way more flexible than before. Also with this change you could remove the delimiter parameter from the signature (and `getPath(obj, 'a>b', 0, '>')` becomes `getPath(obj, 'a>b'.split('>'), 0)`), but I understand that to keep backwards compatibility, you preserve it.

What do you think?

Bests,
Dani

**Comment by skratchdot** [comment]
I'm fine with supporting both formats (array and string paths), but I'd also need to update the `object-path-set` library as well.  I believe there are already some libraries that support the "array" version that have a pretty big user base.

I don't, however, want to remove the string support (because I have quite a few libraries that use the lib in that fashion).  It's easier/quicker for me to type:
`getPath(obj, 'some.long.path.that.i.know')`
than:
`getPath(obj, 'some.long.path.that.i.know'.split('.'))`
or:
`getPath(obj, ['some', 'long', 'path', 'that', 'i', 'know'])`

I know I'm not saving that many keystrokes, but does help :)

Seems like I could support both `string` and `array` without too many problems.

**Comment by danigb** [comment]
Great. I didn't suggest to remove string support, only the possibility to remove de "delimiting parameter" option (and support only dots as separator and arrays). Anyway I think string and array could live together without problems.

So, do you want a PR on this? Maybe I can PR object-path-set too...

Just curious, what are the other libraries with the big user base you're talking about?

**Comment by skratchdot** [comment]
hmm.  It actually looks like lodash supports an almost identical signature now (that supports both strings and arrays): https://lodash.com/docs#get

I can't really remember the library that only supports arrays- but I remember using a lib that found some "deep keys" via an array, and I looked at the source to see which library it was using.  It was something other than lodash that was specific to finding deep values using an array of keys (but I can't remember the name ATM)!

**Comment by skratchdot** [comment]
I know immutable js has a `getIn()` function that uses arrays.  I wish I could remember the name of the library that I was thinking of...
